export const Sprites = {
  CornerEmpty: require('../Assets/Sprites/empty_corner_placeholder.png'),
  CornerSolid: require('../Assets/Sprites/solid_corner_placeholder.png'),
  Crystal: require('../Assets/Sprites/crystal_placeholder.png'),
  FloorEmpty: require('../Assets/Sprites/empty_floor_placeholder.png'),
  FloorSemisolid: require('../Assets/Sprites/semisolid_floor_placeholder.png'),
  FloorSolid: require('../Assets/Sprites/solid_floor_placeholder.png'),
  PlayerAttack: require('../Assets/Sprites/player_attack_placeholder.png'),
  PlayerIdle: require('../Assets/Sprites/player_idle_placeholder.png'),
  PlayerWarp: require('../Assets/Sprites/player_warp_placeholder.png'),
  RoomEmpty: require('../Assets/Sprites/empty_room_placeholder.png'),
  RoomStairs: require('../Assets/Sprites/stairs_room_placeholder.png'),
  Vignette: require('../Assets/Sprites/vignette.png'),
  WallEmpty: require('../Assets/Sprites/empty_wall_placeholder.png'),
  WallSolid: require('../Assets/Sprites/solid_wall_placeholder.png'),
};